# Generated by Django 3.0.5 on 2020-11-02 20:06

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_friend', models.CharField(max_length=250)),
                ('sender_friend', models.CharField(max_length=250)),
                ('receiver_friend_obj', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_friend_obj', to=settings.AUTH_USER_MODEL)),
                ('sender_friend_obj', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_friend_obj', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
