# Generated by Django 3.0.5 on 2020-11-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_friend', models.CharField(max_length=250)),
                ('sender_friend', models.CharField(max_length=250)),
            ],
        ),
    ]
