# Generated by Django 3.0.5 on 2020-11-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='postFile/'),
        ),
    ]
