# Generated by Django 3.0.5 on 2020-11-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='image',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='postFile/'),
        ),
    ]
