# Generated by Django 3.0.5 on 2020-11-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprivacy'),
        ('accounts', '0002_userprivacy'),
    ]

    operations = [
    ]
