# Generated by Django 3.0.5 on 2020-11-26 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201117_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('private_profile', models.BooleanField(default=False)),
                ('show_email_on_profile', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
