# Generated by Django 3.0.5 on 2020-12-02 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201202_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='postFile/'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.Page'),
        ),
    ]
