# Generated by Django 3.0.5 on 2020-12-08 01:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201204_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='private_profile',
        ),
        migrations.AddField(
            model_name='userpost',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='postFile/'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.Page'),
        ),
    ]
